### ISSUE TITLE
A few issues.

### ISSUE THREAD

**Issue by Dorian1334** [NinjaSiren/Yes-Vehicles-finally#1]
Unfortunately, the mod isn't exactly functional. For starters, you can't un-load any one you put inside, and secondly (a graphical issue) the vehicles don't face the correct directions when moving. They seem to prefer facing up or down, regardless of direction they're traveling in.

**Comment by Cacrushgamer** [comment]
Did you find a fix of how to exit the vehicle or no?

**Comment by NinjaSiren** [comment]
This will never be fixed until JecsTools is completely finished. Waiting for it.

**Comment by murmax** [comment]
Same about directions (may it be connected with that fact, that in B18 Yes, vehicles .png files were named in other way, than now?). But I haven't got a problem with entering/exiting from vehicles. But it is needed an instruction how to form caravan, because caravan itself cannot be formed from only a truck and truck cannot be applied to caravan while nobody inside. On the other hand when my colonist is inside, he is not in reality and that breaks a lot. Two colonists can go in caravan with truck (one inside, other outside), but What's with speed then? It calculates a middle speed of everybody in caravan (like Bob 15 km/h, Masha 14 km/h, Truck 160 km/h, middle is: 63. I don't think it should work like that.

**Comment by NinjaSiren** [comment]
In the XML files that the mod has only show speed similar to speed of an
animal pawn. But most of the issues will only be fixed until JecsTools
CompVehicle codes be fully finished.

**Comment by murmax** [comment]
About strange vehicle positioning, I think I found why it happened. There are some mistakes in naming .png texture files. South and north are named uncorrectly and there are no _side files in v1.0, it should be named _east (see screen below)
![image](https://user-images.githubusercontent.com/23609822/61596009-99b3f600-ac06-11e9-8825-b4c497427ccc.png)

**Comment by NinjaSiren** [comment]
I just followed the original mod author's flow and file naming. I know that
v1.0 changed it.

Overall the textures work with the XML files that was originally made by
Mason J Caboose. It might not be efficient, or clean looking, but it works.

My major concern is not the textures currently, it's the weapon and overall
operation of the mod. That means waiting for JecsTools to be fully
functional.
